Repository toml-lang/toml, pull requests merged in 2019-11, with the labels that each got.

#676 Allow heterogeneous arrays
  README.md
Labels: enhancement

#673 Make the ABNF syntax tree, more semantic for ml-basic-string
  toml.abnf
Labels: abnf

#680 Clarify when array of tables ends
  README.md
Labels: clarification
